# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kat King
email: katkingcodes@gmail.com
music_email: katkingmusic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kat King is a musician, software developer, explorer and pal. She
  likes to try hard and, at times, fail magestically.
baseurl: "" # the subpath of your site, e.g. /blog
local_url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
url: "coderkat.github.io"
twitter_username: satchkat
github_username:  coderkat

# Enforce SSL
url: https://katking.me   # with the https protocol
enforce_ssl: katking.me   # without any protocol

# Build settings
# Standard markdown:
markdown: kramdown

# Include plugins
gems:
  - jekyll-sitemap

collections:
    travel:
        output: true

# use this markdown if using jekyll-picture-tag:
# markdown: redcarpet
# picture:
#   source: "assets/images"
#   output: "generated"
#   markup: "picture"
#   presets:
#     default:
#     main:
#     gallery:
